Add changes from club session + improvements
UMLCloudComputing/UniPath.io pull request #65
Opened 2023-11-18 02:01 UTC by MartinMarwad

Add changes worked during club session, plus a few other improvements and cleanups.

2023-11-18 02:16 UTC, Gurpranked requested changes
Please review the comment placed on the signup/page.js file to fix the current build errors. 
Overall valuable edits, just a small typo.

2023-11-18 02:16 UTC, Gurpranked commented on src/app/(auth)/signup/page.js
Small typo in the CSS Baseline import statement. Should be `import CssBaseline from '@mui/material/CssBaseline` as stated in the following MUI docs page: https://mui.com/material-ui/react-css-baseline/. 
Hope it helps

2023-11-18 02:21 UTC, MartinMarwad commented on src/app/(auth)/signup/page.js
Latest commit 4a44ebe fixed this 👍

2023-11-18 02:22 UTC, Gurpranked commented on src/app/(auth)/signup/page.js
Nice!

2023-11-18 02:22 UTC, Gurpranked commented on src/app/(auth)/signup/page.js
I still see some errors with the deployed application, not sure if it's just on my end.

2023-11-18 02:23 UTC, Gurpranked approved these changes

2023-11-18 02:24 UTC, Gurpranked commented on src/app/(auth)/signup/page.js
Nevermind, it was just Amplify taking longer than expected to build all the dependencies. Looks good!

2023-11-20 21:46 UTC, andrew-aiken approved these changes
Probably is good

2023-11-20 21:47 UTC, merged